; QR Terminal v2 — Computer v2, 32 KB. Generated by build.py.
; CPU computes payload, Reed–Solomon, interleaving, matrix and terminal raster.
ret0_bank equ 25
ret0_addr equ 26
ret1_bank equ 27
ret1_addr equ 28
ret2_bank equ 29
ret2_addr equ 30
ret3_bank equ 31
ret3_addr equ 32
io_ret_bank equ 33
PC_BANK equ 34
PC_ADDR equ 35
SP equ 36
RSP equ 37
U0 equ 38
U1 equ 39
V0 equ 40
V1 equ 41
W0 equ 42
W1 equ 43
M0 equ 44
M1 equ 45
opcode equ 46
roll equ 47
x0 equ 48
y0 equ 49
x1 equ 50
y1 equ 51
dx equ 52
dy equ 53
sx equ 54
sy equ 55
t0 equ 56
t1 equ 57
spare0 equ 58
spare1 equ 59
qptr0 equ 64
qptr1 equ 65
qpack equ 66
qpackn equ 67
qcount equ 68
qword0 equ 69
qword1 equ 70
qskip equ 71
qvalue equ 72
qleft0 equ 73
qleft1 equ 74
qout0 equ 75
qout1 equ 76
qcoef0 equ 77
qcoef1 equ 78
qdegree equ 79
qfactor equ 80
qindex equ 81
gf_b equ 82
gf_log equ 83
qx equ 84
qy equ 85
qsize equ 86
qright equ 87
qbit equ 88
qup equ 89
qcolumns equ 90
qbyte equ 91
qrowbase equ 92
qextent equ 93
qwidth equ 94
qphysicalx equ 95
qphysicaly equ 75
qbank equ 69
DISPATCH_BANK equ 30
STACK_BANK equ 31
RETURN_STACK_BANK equ 32
GLOBAL_WORDS_BANK equ 33
STRINGS_BANK equ 41
INPUT_BANK equ 49
DATA_BANK equ 55
ECC_BANK equ 58
STREAM_BANK equ 60
BLOCK_INFO_BANK equ 63
MATRIX_BANK equ 64
LOG_BANK equ 96
EXP_BANK equ 98
ALPHABET_MAP_BANK equ 102
EC_LETTERS_BANK equ 104
PROFILES_BANK equ 106
PROGRAM_BANK equ 116
DATA_LO equ 128
DATA_HI equ 27
STREAM_LO equ 0
STREAM_HI equ 30
APP_BANK equ 3
RS_REGISTER equ 96
start: ldi c, APP_BANK
st c, 63
jmp main
set_bank: st c, 63
jmp d
read_byte: st c, 63
ld a, b
ld c, io_ret_bank
st c, 63
jmp d
write_byte: st c, 63
st a, b
ld c, io_ret_bank
st c, 63
jmp d
word_workspace db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ports db 0,0,1,0
qr_workspace db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
rs_register db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

; Native bank 1
; QR Terminal v2 native QR engine
op_fill:
ldi c, 1
st c, ret2_bank
ldi d, resume_op_fill_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_fill_0:
ld a, U0
st a, qvalue
ldi c, 1
st c, ret2_bank
ldi d, resume_op_fill_3
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_fill_3:
ld a, U0
st a, qleft0
ld a, U1
st a, qleft1
ldi c, 1
st c, ret2_bank
ldi d, resume_op_fill_8
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_fill_8:
ld a, U0
st a, M0
ld a, U1
st a, M1
fill_loop:
ld a, qleft0
ld b, qleft1
or a, b
jnz bridge_op_fill_17
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
bridge_op_fill_17:
ld a, qvalue
ldi c, 1
st c, ret3_bank
ldi d, resume_op_fill_19
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_op_fill_19:
ldi c, 1
st c, ret3_bank
ldi d, resume_op_fill_20
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_op_fill_20:
ld a, qleft0
ldi b, 1
sub a, b
st a, qleft0
ld a, qleft1
ldi b, 0
sbb a, b
st a, qleft1
jmp fill_loop
padding1 db 0,0,0,0,0,0,0

; Native bank 2
; QR Terminal v2 native QR engine
op_rsblock:
ldi c, 2
st c, ret2_bank
ldi d, resume_op_rsblock_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_rsblock_0:
ld a, U0
st a, qout0
ld a, U1
st a, qout1
ldi c, 2
st c, ret2_bank
ldi d, resume_op_rsblock_5
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_rsblock_5:
ld a, U0
st a, qcoef0
ld a, U1
st a, qcoef1
ldi c, 2
st c, ret2_bank
ldi d, resume_op_rsblock_10
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_rsblock_10:
ld a, U0
st a, qdegree
ldi c, 2
st c, ret2_bank
ldi d, resume_op_rsblock_13
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_rsblock_13:
ld a, U0
st a, qleft0
ldi c, 2
st c, ret2_bank
ldi d, resume_op_rsblock_16
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_rsblock_16:
ld a, U0
st a, qptr0
ld a, U1
st a, qptr1
clr a
ldi b, RS_REGISTER
ldi c, 31
rs_clear:
st a, b
inc b
dec c
jnz rs_clear
ldi c, 17
ldi d, rs_outer
jmp set_bank
; QR Terminal v2 word runtime
op_div:
clr a
st a, opcode
ldi c, 13
ldi d, vm_divide
jmp set_bank
padding2 db 0

; Native bank 3
; QR Terminal v2 native QR engine
place_module:
ldi c, 3
st c, ret1_bank
ldi d, resume_place_module_0
st d, ret1_addr
ldi c, 22
ldi d, qr_get
jmp set_bank
resume_place_module_0:
ldi b, 2
and a, b
jz bridge_place_module_3
ldi c, 18
ldi d, place_next
jmp set_bank
bridge_place_module_3:
ld a, qleft0
ld b, qleft1
or a, b
jnz bridge_place_module_7
ldi c, 18
ldi d, place_next
jmp set_bank
bridge_place_module_7:
ld a, qbit
ldi b, 128
xor b, a
jz bridge_place_module_11
ldi c, 16
ldi d, place_color
jmp set_bank
bridge_place_module_11:
ld a, qptr0
st a, M0
ld a, qptr1
st a, M1
ldi c, 3
st c, ret3_bank
ldi d, resume_place_module_16
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_place_module_16:
st a, qbyte
ldi c, 3
st c, ret3_bank
ldi d, resume_place_module_18
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_place_module_18:
ld a, M0
st a, qptr0
ld a, M1
st a, qptr1
ldi c, 16
ldi d, native_continuation_1
jmp set_bank
; QR Terminal v2 word runtime
main:
ldi a, PROGRAM_BANK
st a, PC_BANK
ldi a, 128
st a, PC_ADDR
clr a
st a, SP
st a, RSP
ldi a, 1
st a, 62
ld a, 62
ldi c, 10
ldi d, vm_dispatch
jmp set_bank

; Native bank 4
; QR Terminal v2 word runtime
op_mul:
ldi c, 4
st c, ret1_bank
ldi d, resume_op_mul_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_mul_0:
clr a
st a, W0
st a, W1
ldi a, 16
st a, roll
mul16_loop:
ld a, V1
shr a
st a, V1
ld a, V0
rcr a
st a, V0
jnc mul16_skip
ld a, W0
ld b, U0
add a, b
st a, W0
ld a, W1
ld b, U1
adc a, b
st a, W1
mul16_skip:
ld a, U0
shl a
st a, U0
ld a, U1
rcl a
st a, U1
ld a, roll
dec a
st a, roll
jnz mul16_loop
ld a, W0
st a, U0
ld a, W1
st a, U1
ldi c, 4
st c, ret2_bank
ldi d, resume_op_mul_37
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_mul_37:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_jump:
ld a, M1
shl a
st a, PC_BANK
ld a, M0
shl a
jnc jump_low
ld a, PC_BANK
inc a
st a, PC_BANK
jump_low:
ld a, M0
ldi b, 128
or a, b
st a, PC_ADDR
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
padding4 db 0,0,0,0,0,0

; Native bank 5
; QR Terminal v2 native QR engine
bits_emit:
ld a, qcount
test a
jnz bridge_bits_emit_2
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
bridge_bits_emit_2:
ld a, qword0
shl a
st a, qword0
ld a, qword1
rcl a
st a, qword1
ld a, qpack
rcl a
st a, qpack
ld a, qpackn
inc a
st a, qpackn
ldi b, 8
xor b, a
jnz bits_next
ld a, qptr0
st a, M0
ld a, qptr1
st a, M1
ld a, qpack
ldi c, 5
st c, ret3_bank
ldi d, resume_bits_emit_23
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_bits_emit_23:
ldi c, 5
st c, ret3_bank
ldi d, resume_bits_emit_24
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_bits_emit_24:
ld a, M0
st a, qptr0
ld a, M1
st a, qptr1
clr a
st a, qpack
st a, qpackn
bits_next:
ld a, qcount
dec a
st a, qcount
jmp bits_emit
; QR Terminal v2 native QR engine
qr_set:
st a, qvalue
ldi c, 5
st c, ret0_bank
ldi d, resume_qr_set_1
st d, ret0_addr
ldi c, 21
ldi d, qr_address
jmp set_bank
resume_qr_set_1:
ld c, qbank
ld a, qvalue
ldi d, 5
st d, io_ret_bank
ldi d, io_qr_set_4
jmp write_byte
io_qr_set_4:
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank

; Native bank 6
; QR Terminal v2 native QR engine
op_mask:
ldi c, 6
st c, ret2_bank
ldi d, resume_op_mask_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_mask_0:
ld a, U0
st a, qsize
clr a
st a, qy
mask_row:
clr a
st a, qx
mask_column:
ld a, qx
ld b, qy
add a, b
shr a
jc mask_next
ldi c, 6
st c, ret1_bank
ldi d, resume_op_mask_14
st d, ret1_addr
ldi c, 22
ldi d, qr_get
jmp set_bank
resume_op_mask_14:
ldi b, 2
and b, a
jnz mask_next
ldi b, 1
xor a, b
ldi c, 6
st c, ret1_bank
ldi d, resume_op_mask_20
st d, ret1_addr
ldi c, 5
ldi d, qr_set
jmp set_bank
resume_op_mask_20:
mask_next:
ld a, qx
inc a
st a, qx
ld b, qsize
xor b, a
jnz mask_column
ld a, qy
inc a
st a, qy
ld b, qsize
xor b, a
jnz mask_row
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_set:
ldi c, 6
st c, ret1_bank
ldi d, resume_op_set_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_set_0:
ldi c, 6
st c, ret2_bank
ldi d, resume_op_set_1
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_set_1:
ldi c, 20
ldi d, vm_store_word
jmp set_bank

; Native bank 7
; QR Terminal v2 native QR engine
rs_inner:
ldi c, 7
st c, ret3_bank
ldi d, resume_rs_inner_0
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_rs_inner_0:
ld b, qfactor
ldi c, 7
st c, ret1_bank
ldi d, resume_rs_inner_2
st d, ret1_addr
ldi c, 8
ldi d, gf_multiply
jmp set_bank
resume_rs_inner_2:
ld b, qindex
ldi c, RS_REGISTER+1
add b, c
ld c, b
xor a, c
dec b
st a, b
ldi c, 7
st c, ret3_bank
ldi d, resume_rs_inner_10
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_rs_inner_10:
ld a, qindex
inc a
st a, qindex
ld b, qdegree
xor b, a
jnz rs_inner
ld a, qleft0
dec a
st a, qleft0
jz bridge_rs_inner_20
ldi c, 17
ldi d, rs_outer
jmp set_bank
bridge_rs_inner_20:
ld a, qout0
st a, M0
ld a, qout1
st a, M1
clr a
st a, qindex
ldi c, 9
ldi d, rs_output
jmp set_bank
; QR Terminal v2 native QR engine
place_pair:
ld a, qright
ldi b, 6
xor b, a
jnz place_pair_ready
dec a
st a, qright
place_pair_ready:
ld a, qsize
dec a
ld b, qup
test b
jnz place_row_start
clr a
place_row_start:
st a, qy
ldi c, 19
ldi d, place_row
jmp set_bank
padding7 db 0,0,0,0,0,0,0,0

; Native bank 8
; QR Terminal v2 native QR engine
gf_multiply:
test a
jz gf_zero
test b
jz gf_zero
st b, gf_b
mov b, a
shl a
ldi c, LOG_BANK
jnc gf_first_low
inc c
gf_first_low:
ldi a, 128
or b, a
ldi d, 8
st d, io_ret_bank
ldi d, io_gf_multiply_13
jmp read_byte
io_gf_multiply_13:
st a, gf_log
ld b, gf_b
mov a, b
shl a
ldi c, LOG_BANK
jnc gf_second_low
inc c
gf_second_low:
ldi a, 128
or b, a
ldi d, 8
st d, io_ret_bank
ldi d, io_gf_multiply_24
jmp read_byte
io_gf_multiply_24:
ld b, gf_log
add a, b
ldi c, EXP_BANK
jnc gf_exp_low
inc c
inc c
gf_exp_low:
mov b, a
shl a
jnc gf_exp_bank
inc c
gf_exp_bank:
ldi a, 128
or b, a
ldi d, 8
st d, io_ret_bank
ldi d, io_gf_multiply_39
jmp read_byte
io_gf_multiply_39:
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank
gf_zero:
clr a
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank
; QR Terminal v2 word runtime
vm_operands:
ldi c, 8
st c, ret2_bank
ldi d, resume_vm_operands_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_vm_operands_0:
ld a, U0
st a, V0
ld a, U1
st a, V1
ldi c, 8
st c, ret2_bank
ldi d, resume_vm_operands_5
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_vm_operands_5:
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank

; Native bank 9
; QR Terminal v2 native QR engine
op_bits:
ldi c, 9
st c, ret2_bank
ldi d, resume_op_bits_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_bits_0:
ld a, U0
st a, qcount
ldi c, 9
st c, ret2_bank
ldi d, resume_op_bits_3
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_bits_3:
ld a, U0
st a, qword0
ld a, U1
st a, qword1
ldi a, 16
ld b, qcount
sub a, b
st a, qskip
jnz bridge_op_bits_12
ldi c, 5
ldi d, bits_emit
jmp set_bank
bridge_op_bits_12:
bits_shift:
ld a, qword0
shl a
st a, qword0
ld a, qword1
rcl a
st a, qword1
ld a, qskip
dec a
st a, qskip
jnz bits_shift
ldi c, 5
ldi d, bits_emit
jmp set_bank
; QR Terminal v2 native QR engine
rs_output:
ld b, qindex
ldi c, RS_REGISTER
add b, c
ld a, b
ldi c, 9
st c, ret3_bank
ldi d, resume_rs_output_4
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_rs_output_4:
ldi c, 9
st c, ret3_bank
ldi d, resume_rs_output_5
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_rs_output_5:
ld a, qindex
inc a
st a, qindex
ld b, qdegree
xor b, a
jnz rs_output
ldi c, 10
ldi d, vm_dispatch
jmp set_bank

; Native bank 10
; QR Terminal v2 native QR engine
op_plot:
ldi c, 10
st c, ret2_bank
ldi d, resume_op_plot_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_plot_0:
ld a, U0
st a, qvalue
ldi c, 10
st c, ret2_bank
ldi d, resume_op_plot_3
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_plot_3:
ld a, U0
st a, qy
ldi c, 10
st c, ret2_bank
ldi d, resume_op_plot_6
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_plot_6:
ld a, U0
st a, qx
ld a, qvalue
ldi c, 10
st c, ret1_bank
ldi d, resume_op_plot_10
st d, ret1_addr
ldi c, 5
ldi d, qr_set
jmp set_bank
resume_op_plot_10:
jmp vm_dispatch
; QR Terminal v2 word runtime
vm_dispatch:
ldi c, 10
st c, ret3_bank
ldi d, resume_vm_dispatch_0
st d, ret3_addr
ldi c, 27
ldi d, vm_fetch
jmp set_bank
resume_vm_dispatch_0:
dec a
shl a
ldi b, 128
add b, a
st b, opcode
ldi c, DISPATCH_BANK
ldi d, 10
st d, io_ret_bank
ldi d, io_vm_dispatch_7
jmp read_byte
io_vm_dispatch_7:
st a, x0
ld b, opcode
inc b
ldi c, DISPATCH_BANK
ldi d, 10
st d, io_ret_bank
ldi d, io_vm_dispatch_12
jmp read_byte
io_vm_dispatch_12:
mov d, a
ld c, x0
jmp set_bank
padding10 db 0,0,0,0,0

; Native bank 11
; QR Terminal v2 native QR engine
op_tile:
ldi c, 11
st c, ret2_bank
ldi d, resume_op_tile_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_tile_0:
ld a, U0
st a, qy
ldi c, 11
st c, ret2_bank
ldi d, resume_op_tile_3
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_tile_3:
ld a, U0
st a, qx
ldi c, 11
st c, ret1_bank
ldi d, resume_op_tile_6
st d, ret1_addr
ldi c, 22
ldi d, qr_get
jmp set_bank
resume_op_tile_6:
st a, U0
clr a
st a, U1
ldi c, 11
st c, ret2_bank
ldi d, resume_op_tile_10
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_tile_10:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_store8:
ldi c, 11
st c, ret1_bank
ldi d, resume_op_store8_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_store8_0:
ld a, U0
st a, M0
ld a, U1
st a, M1
ld a, V0
st a, U0
ld a, V1
st a, U1
ld a, U0
ldi c, 11
st c, ret3_bank
ldi d, resume_op_store8_10
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_op_store8_10:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
padding11 db 0

; Native bank 12
; QR Terminal v2 word runtime
op_lt:
ldi c, 12
st c, ret1_bank
ldi d, resume_op_lt_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_lt_0:
ld a, U1
ld b, V1
xor a, b
js lt_opposite
ld a, U1
sub a, b
jc lt_yes
jnz lt_no
ld a, U0
ld b, V0
sub a, b
jc lt_yes
jmp lt_no
lt_opposite:
ld a, U1
test a
js lt_yes
lt_no:
clr a
jmp lt_done
lt_yes:
ldi a, 1
lt_done:
st a, U0
clr a
st a, U1
ldi c, 12
st c, ret2_bank
ldi d, resume_op_lt_27
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_lt_27:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_shr:
ldi c, 12
st c, ret1_bank
ldi d, resume_op_shr_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_shr_0:
ld a, V0
test a
jz shr_done
shr_loop:
ld a, U1
sar a
st a, U1
ld a, U0
rcr a
st a, U0
ld a, V0
dec a
st a, V0
jnz shr_loop
shr_done:
ldi c, 12
st c, ret2_bank
ldi d, resume_op_shr_16
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_shr_16:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank

; Native bank 13
; QR Terminal v2 word runtime
vm_divide:
ldi c, 13
st c, ret1_bank
ldi d, resume_vm_divide_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_vm_divide_0:
ld a, U1
st a, sx
ld b, V1
xor a, b
st a, sy
ld a, U1
test a
jns div_u_positive
ld a, U0
neg a
st a, U0
ld a, U1
ldi b, 0
sbb b, a
st b, U1
div_u_positive:
ld a, V1
test a
jns div_v_positive
ld a, V0
neg a
st a, V0
ld a, V1
ldi b, 0
sbb b, a
st b, V1
div_v_positive:
clr a
st a, W0
st a, W1
ldi a, 16
st a, roll
ldi c, 16
ldi d, vm_division_loop
jmp set_bank
; QR Terminal v2 word runtime
op_shl:
ldi c, 13
st c, ret1_bank
ldi d, resume_op_shl_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_shl_0:
ld a, V0
test a
jz shl_done
shl_loop:
ld a, U0
shl a
st a, U0
ld a, U1
rcl a
st a, U1
ld a, V0
dec a
st a, V0
jnz shl_loop
shl_done:
ldi c, 13
st c, ret2_bank
ldi d, resume_op_shl_16
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_shl_16:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank

; Native bank 14
; QR Terminal v2 native QR engine
render_pixel:
ld a, qphysicalx
ldi b, 4
sub a, b
jc render_blank
st a, qx
ld b, qsize
sub a, b
jnc render_blank
ld a, qphysicaly
ldi b, 4
sub a, b
jc render_blank
st a, qy
ld b, qsize
sub a, b
jnc render_blank
ldi c, 14
st c, ret1_bank
ldi d, resume_render_pixel_16
st d, ret1_addr
ldi c, 22
ldi d, qr_get
jmp set_bank
resume_render_pixel_16:
shr a
jnc render_blank
ld a, qpack
ld b, qbit
or a, b
st a, qpack
render_blank:
ld a, qphysicaly
inc a
st a, qphysicaly
ld a, qbit
shl a
st a, qbit
jnz render_pixel
ldi c, 24
ldi d, render_emit
jmp set_bank
; QR Terminal v2 word runtime
op_text:
ldi c, 14
st c, ret1_bank
ldi d, resume_op_text_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_text_0:
text_loop:
ldi c, 14
st c, ret3_bank
ldi d, resume_op_text_2
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_op_text_2:
test a
jz text_done
st a, 60
ldi c, 14
st c, ret3_bank
ldi d, resume_op_text_6
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_op_text_6:
jmp text_loop
text_done:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
padding14 db 0,0,0

; Native bank 15
; QR Terminal v2 word runtime
vm_load_word:
ldi c, 15
st c, ret3_bank
ldi d, resume_vm_load_word_0
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_vm_load_word_0:
st a, U0
ldi c, 15
st c, ret3_bank
ldi d, resume_vm_load_word_2
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_vm_load_word_2:
ldi c, 15
st c, ret3_bank
ldi d, resume_vm_load_word_3
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_vm_load_word_3:
st a, U1
ldi c, 15
st c, ret2_bank
ldi d, resume_vm_load_word_5
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_vm_load_word_5:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_call:
ldi c, 15
st c, ret1_bank
ldi d, resume_op_call_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_call_0:
ld b, RSP
ldi a, 128
add b, a
ldi c, RETURN_STACK_BANK
ld a, PC_BANK
ldi d, 15
st d, io_ret_bank
ldi d, io_op_call_6
jmp write_byte
io_op_call_6:
ld b, RSP
ldi a, 129
add b, a
ldi c, RETURN_STACK_BANK
ld a, PC_ADDR
ldi d, 15
st d, io_ret_bank
ldi d, io_op_call_12
jmp write_byte
io_op_call_12:
ld a, RSP
inc a
inc a
st a, RSP
ldi c, 4
ldi d, vm_jump
jmp set_bank
padding15 db 0,0

; Native bank 16
; QR Terminal v2 word runtime
vm_division_loop:
ld a, U0
shl a
st a, U0
ld a, U1
rcl a
st a, U1
ld a, W0
rcl a
st a, W0
ld a, W1
rcl a
st a, W1
ld b, V1
sub a, b
jc div_skip
jnz div_subtract
ld a, W0
ld b, V0
sub a, b
jc div_skip
div_subtract:
ld a, W0
ld b, V0
sub a, b
st a, W0
ld a, W1
ld b, V1
sbb a, b
st a, W1
ld a, U0
inc a
st a, U0
div_skip:
ld a, roll
dec a
st a, roll
jnz vm_division_loop
ldi c, 19
ldi d, vm_division_done
jmp set_bank
; QR Terminal v2 native QR engine
native_continuation_1:
place_color:
ld a, qbyte
ld b, qbit
and a, b
ldi a, 0
jz place_write
inc a
place_write:
ldi c, 16
st c, ret1_bank
ldi d, resume_native_continuation_1_8
st d, ret1_addr
ldi c, 5
ldi d, qr_set
jmp set_bank
resume_native_continuation_1_8:
ld a, qbit
shr a
st a, qbit
jz bridge_native_continuation_1_12
ldi c, 18
ldi d, place_next
jmp set_bank
bridge_native_continuation_1_12:
ldi a, 128
st a, qbit
ld a, qleft0
ldi b, 1
sub a, b
st a, qleft0
ld a, qleft1
ldi b, 0
sbb a, b
st a, qleft1
ldi c, 18
ldi d, place_next
jmp set_bank
padding16 db 0

; Native bank 17
; QR Terminal v2 native QR engine
rs_outer:
ld a, qptr0
st a, M0
ld a, qptr1
st a, M1
ldi c, 17
st c, ret3_bank
ldi d, resume_rs_outer_4
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_rs_outer_4:
ld b, RS_REGISTER
xor a, b
st a, qfactor
ldi c, 17
st c, ret3_bank
ldi d, resume_rs_outer_8
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_rs_outer_8:
ld a, M0
st a, qptr0
ld a, M1
st a, qptr1
ld a, qcoef0
st a, M0
ld a, qcoef1
st a, M1
clr a
st a, qindex
ldi c, 7
ldi d, rs_inner
jmp set_bank
; QR Terminal v2 word runtime
op_load8:
ldi c, 17
st c, ret2_bank
ldi d, resume_op_load8_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_load8_0:
ld a, U0
st a, M0
ld a, U1
st a, M1
ldi c, 17
st c, ret3_bank
ldi d, resume_op_load8_5
st d, ret3_addr
ldi c, 25
ldi d, vm_read
jmp set_bank
resume_op_load8_5:
st a, U0
clr b
st b, U1
ldi c, 17
st c, ret2_bank
ldi d, resume_op_load8_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_load8_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
padding17 db 0

; Native bank 18
; QR Terminal v2 native QR engine
op_place:
ldi c, 18
st c, ret2_bank
ldi d, resume_op_place_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_place_0:
ld a, U0
st a, qleft0
ld a, U1
st a, qleft1
ldi c, 18
st c, ret2_bank
ldi d, resume_op_place_5
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_place_5:
ld a, U0
st a, qsize
dec a
st a, qright
ldi a, STREAM_LO
st a, qptr0
ldi a, STREAM_HI
st a, qptr1
ldi a, 128
st a, qbit
ldi a, 1
st a, qup
ldi c, 7
ldi d, place_pair
jmp set_bank
; QR Terminal v2 native QR engine
place_next:
ld a, qx
dec a
st a, qx
ld a, qcolumns
dec a
st a, qcolumns
jz bridge_place_next_6
ldi c, 3
ldi d, place_module
jmp set_bank
bridge_place_next_6:
ld a, qy
ld b, qup
test b
jz place_down
test a
jnz bridge_place_next_12
ldi c, 28
ldi d, place_end_pair
jmp set_bank
bridge_place_next_12:
dec a
st a, qy
ldi c, 19
ldi d, place_row
jmp set_bank
place_down:
inc a
st a, qy
ld b, qsize
xor b, a
jz bridge_place_next_21
ldi c, 19
ldi d, place_row
jmp set_bank
bridge_place_next_21:
ldi c, 28
ldi d, place_end_pair
jmp set_bank

; Native bank 19
; QR Terminal v2 word runtime
op_eq:
ldi c, 19
st c, ret1_bank
ldi d, resume_op_eq_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_eq_0:
ld a, U0
ld b, V0
xor a, b
st a, W0
ld a, U1
ld b, V1
xor a, b
ld b, W0
or a, b
ldi a, 0
jnz eq_done
inc a
eq_done:
st a, U0
clr a
st a, U1
ldi c, 19
st c, ret2_bank
ldi d, resume_op_eq_17
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_eq_17:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_division_done:
ld a, opcode
test a
jz div_quotient
ld a, W0
st a, U0
ld a, W1
st a, U1
ld a, sx
jmp div_sign
div_quotient:
ld a, sy
div_sign:
test a
jns div_finish
ld a, U0
neg a
st a, U0
ld a, U1
ldi b, 0
sbb b, a
st b, U1
div_finish:
ldi c, 19
st c, ret2_bank
ldi d, resume_vm_division_done_22
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_vm_division_done_22:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 native QR engine
place_row:
ld a, qright
st a, qx
ldi a, 2
st a, qcolumns
ldi c, 3
ldi d, place_module
jmp set_bank
padding19 db 0

; Native bank 20
; QR Terminal v2 word runtime
vm_store_word:
ld a, U0
ldi c, 20
st c, ret3_bank
ldi d, resume_vm_store_word_1
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_vm_store_word_1:
ldi c, 20
st c, ret3_bank
ldi d, resume_vm_store_word_2
st d, ret3_addr
ldi c, 29
ldi d, vm_increment_address
jmp set_bank
resume_vm_store_word_2:
ld a, U1
ldi c, 20
st c, ret3_bank
ldi d, resume_vm_store_word_4
st d, ret3_addr
ldi c, 27
ldi d, vm_write
jmp set_bank
resume_vm_store_word_4:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_not:
ldi c, 20
st c, ret2_bank
ldi d, resume_op_not_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_not_0:
ld a, U0
ld b, U1
or a, b
ldi a, 0
jnz not_done
inc a
not_done:
st a, U0
clr a
st a, U1
ldi c, 20
st c, ret2_bank
ldi d, resume_op_not_11
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_not_11:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_address:
ld a, M1
shl a
mov c, a
ld b, M0
shl b
jnc vm_address_low
inc c
vm_address_low:
ld b, M0
test c
jnz vm_address_banked
test b
jns vm_address_done
vm_address_banked:
ldi a, 128
or b, a
vm_address_done:
ld c, ret3_bank
ld d, ret3_addr
jmp set_bank

; Native bank 21
; QR Terminal v2 word runtime
op_add:
ldi c, 21
st c, ret1_bank
ldi d, resume_op_add_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_add_0:
ld a, U0
ld b, V0
add a, b
st a, U0
ld a, U1
ld b, V1
adc a, b
st a, U1
ldi c, 21
st c, ret2_bank
ldi d, resume_op_add_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_add_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_sub:
ldi c, 21
st c, ret1_bank
ldi d, resume_op_sub_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_sub_0:
ld a, U0
ld b, V0
sub a, b
st a, U0
ld a, U1
ld b, V1
sbb a, b
st a, U1
ldi c, 21
st c, ret2_bank
ldi d, resume_op_sub_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_sub_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 native QR engine
qr_address:
ld a, qy
shr a
ldi c, MATRIX_BANK
add c, a
ld a, qy
ldi b, 1
and a, b
shr a
ldi b, 128
jnc qr_address_x
ldi b, 192
qr_address_x:
ld a, qx
add b, a
st c, qbank
ld c, ret0_bank
ld d, ret0_addr
jmp set_bank
padding21 db 0,0,0

; Native bank 22
; QR Terminal v2 word runtime
op_and:
ldi c, 22
st c, ret1_bank
ldi d, resume_op_and_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_and_0:
ld a, U0
ld b, V0
and a, b
st a, U0
ld a, U1
ld b, V1
and a, b
st a, U1
ldi c, 22
st c, ret2_bank
ldi d, resume_op_and_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_and_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_or:
ldi c, 22
st c, ret1_bank
ldi d, resume_op_or_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_or_0:
ld a, U0
ld b, V0
or a, b
st a, U0
ld a, U1
ld b, V1
or a, b
st a, U1
ldi c, 22
st c, ret2_bank
ldi d, resume_op_or_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_or_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 native QR engine
qr_get:
ldi c, 22
st c, ret0_bank
ldi d, resume_qr_get_0
st d, ret0_addr
ldi c, 21
ldi d, qr_address
jmp set_bank
resume_qr_get_0:
ld c, qbank
ldi d, 22
st d, io_ret_bank
ldi d, io_qr_get_2
jmp read_byte
io_qr_get_2:
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank
padding22 db 0,0

; Native bank 23
; QR Terminal v2 word runtime
op_xor:
ldi c, 23
st c, ret1_bank
ldi d, resume_op_xor_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_xor_0:
ld a, U0
ld b, V0
xor a, b
st a, U0
ld a, U1
ld b, V1
xor a, b
st a, U1
ldi c, 23
st c, ret2_bank
ldi d, resume_op_xor_9
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_xor_9:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_dup:
ldi c, 23
st c, ret2_bank
ldi d, resume_op_dup_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_dup_0:
ldi c, 23
st c, ret2_bank
ldi d, resume_op_dup_1
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_dup_1:
ldi c, 23
st c, ret2_bank
ldi d, resume_op_dup_2
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_dup_2:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_key:
vm_key_wait:
ld a, 62
test a
jz vm_key_wait
st a, U0
clr a
st a, U1
ldi c, 23
st c, ret2_bank
ldi d, resume_op_key_7
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_key_7:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
padding23 db 0,0

; Native bank 24
; QR Terminal v2 native QR engine
render_emit:
ld a, qpack
st a, 61
ld a, qphysicalx
inc a
st a, qphysicalx
ld b, qwidth
xor b, a
jz bridge_render_emit_7
ldi c, 29
ldi d, render_column
jmp set_bank
bridge_render_emit_7:
ldi a, 10
st a, 60
ld a, qrowbase
ldi b, 8
add a, b
st a, qrowbase
ld b, qextent
sub a, b
jc render_row
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_jz:
ldi c, 24
st c, ret1_bank
ldi d, resume_op_jz_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_jz_0:
ldi c, 24
st c, ret2_bank
ldi d, resume_op_jz_1
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_jz_1:
ld a, U0
ld b, U1
or a, b
jnz bridge_op_jz_5
ldi c, 4
ldi d, vm_jump
jmp set_bank
bridge_op_jz_5:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_load16:
ldi c, 24
st c, ret2_bank
ldi d, resume_op_load16_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_load16_0:
ld a, U0
st a, M0
ld a, U1
st a, M1
ldi c, 15
ldi d, vm_load_word
jmp set_bank
; QR Terminal v2 native QR engine
render_row:
clr a
st a, qphysicalx
ldi c, 29
ldi d, render_column
jmp set_bank
padding24 db 0,0

; Native bank 25
; QR Terminal v2 native QR engine
op_render:
ldi c, 25
st c, ret2_bank
ldi d, resume_op_render_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_render_0:
ld a, U0
st a, qsize
ldi b, 8
add a, b
st a, qextent
clr a
render_width:
ldi b, 6
add a, b
ld b, qextent
sub b, a
jc render_width_ready
jz render_width_ready
jmp render_width
render_width_ready:
st a, qwidth
clr a
st a, qrowbase
ldi c, 24
ldi d, render_row
jmp set_bank
; QR Terminal v2 word runtime
vm_push:
ld b, SP
ldi a, 128
add b, a
ldi c, STACK_BANK
ld a, U0
ldi d, 25
st d, io_ret_bank
ldi d, io_vm_push_5
jmp write_byte
io_vm_push_5:
ld b, SP
ldi a, 129
add b, a
ldi c, STACK_BANK
ld a, U1
ldi d, 25
st d, io_ret_bank
ldi d, io_vm_push_11
jmp write_byte
io_vm_push_11:
ld a, SP
inc a
inc a
st a, SP
ld c, ret2_bank
ld d, ret2_addr
jmp set_bank
; QR Terminal v2 word runtime
vm_read:
ld a, M1
shl a
mov c, a
ld b, M0
shl b
jnc vm_read_low
inc c
vm_read_low:
ld b, M0
test c
jnz vm_read_banked
test b
jns vm_read_done
vm_read_banked:
ldi a, 128
or b, a
vm_read_done:
ldi d, 25
st d, io_ret_bank
ldi d, io_vm_read_17
jmp read_byte
io_vm_read_17:
ld c, ret3_bank
ld d, ret3_addr
jmp set_bank

; Native bank 26
; QR Terminal v2 word runtime
op_neg:
ldi c, 26
st c, ret2_bank
ldi d, resume_op_neg_0
st d, ret2_addr
jmp vm_pop
resume_op_neg_0:
ld a, U0
neg a
st a, U0
ld a, U1
ldi b, 0
sbb b, a
st b, U1
ldi c, 26
st c, ret2_bank
ldi d, resume_op_neg_8
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_neg_8:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_pop:
ld b, SP
dec b
dec b
st b, SP
ldi a, 128
add b, a
ldi c, STACK_BANK
ldi d, 26
st d, io_ret_bank
ldi d, io_vm_pop_7
jmp read_byte
io_vm_pop_7:
st a, U0
ld b, SP
ldi a, 129
add b, a
ldi c, STACK_BANK
ldi d, 26
st d, io_ret_bank
ldi d, io_vm_pop_13
jmp read_byte
io_vm_pop_13:
st a, U1
ld c, ret2_bank
ld d, ret2_addr
jmp set_bank
; QR Terminal v2 word runtime
op_const:
ldi c, 26
st c, ret1_bank
ldi d, resume_op_const_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_const_0:
ld a, M0
st a, U0
ld a, M1
st a, U1
ldi c, 26
st c, ret2_bank
ldi d, resume_op_const_5
st d, ret2_addr
ldi c, 25
ldi d, vm_push
jmp set_bank
resume_op_const_5:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank

; Native bank 27
; QR Terminal v2 word runtime
op_ret:
ld b, RSP
dec b
dec b
st b, RSP
ldi a, 128
add b, a
ldi c, RETURN_STACK_BANK
ldi d, 27
st d, io_ret_bank
ldi d, io_op_ret_7
jmp read_byte
io_op_ret_7:
st a, PC_BANK
ld b, RSP
ldi a, 129
add b, a
ldi c, RETURN_STACK_BANK
ldi d, 27
st d, io_ret_bank
ldi d, io_op_ret_13
jmp read_byte
io_op_ret_13:
st a, PC_ADDR
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_write:
st a, t0
ld a, M1
shl a
mov c, a
ld b, M0
shl b
jnc vm_write_low
inc c
vm_write_low:
ld b, M0
test c
jnz vm_write_banked
test b
jns vm_write_done
vm_write_banked:
ldi a, 128
or b, a
vm_write_done:
ld a, t0
ldi d, 27
st d, io_ret_bank
ldi d, io_vm_write_19
jmp write_byte
io_vm_write_19:
ld c, ret3_bank
ld d, ret3_addr
jmp set_bank
; QR Terminal v2 word runtime
vm_fetch:
ld c, PC_BANK
ld b, PC_ADDR
ldi d, 27
st d, io_ret_bank
ldi d, io_vm_fetch_2
jmp read_byte
io_vm_fetch_2:
st a, t1
ld b, PC_ADDR
inc b
st b, PC_ADDR
jnz vm_fetch_done
ldi b, 128
st b, PC_ADDR
ld b, PC_BANK
inc b
st b, PC_BANK
vm_fetch_done:
ld a, t1
ld c, ret3_bank
ld d, ret3_addr
jmp set_bank
padding27 db 0,0,0,0,0,0,0

; Native bank 28
; QR Terminal v2 word runtime
vm_immediate:
ldi c, 28
st c, ret3_bank
ldi d, resume_vm_immediate_0
st d, ret3_addr
ldi c, 27
ldi d, vm_fetch
jmp set_bank
resume_vm_immediate_0:
st a, M0
ldi c, 28
st c, ret3_bank
ldi d, resume_vm_immediate_2
st d, ret3_addr
ldi c, 27
ldi d, vm_fetch
jmp set_bank
resume_vm_immediate_2:
st a, M1
ld c, ret1_bank
ld d, ret1_addr
jmp set_bank
; QR Terminal v2 word runtime
op_store16:
ldi c, 28
st c, ret1_bank
ldi d, resume_op_store16_0
st d, ret1_addr
ldi c, 8
ldi d, vm_operands
jmp set_bank
resume_op_store16_0:
ld a, U0
st a, M0
ld a, U1
st a, M1
ld a, V0
st a, U0
ld a, V1
st a, U1
ldi c, 20
ldi d, vm_store_word
jmp set_bank
; QR Terminal v2 native QR engine
place_end_pair:
ld a, qup
ldi b, 1
xor a, b
st a, qup
ld a, qright
ldi b, 2
sub a, b
st a, qright
jnc bridge_place_end_pair_8
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
bridge_place_end_pair_8:
jnz bridge_place_end_pair_9
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
bridge_place_end_pair_9:
ldi c, 7
ldi d, place_pair
jmp set_bank
; QR Terminal v2 word runtime
op_get:
ldi c, 28
st c, ret1_bank
ldi d, resume_op_get_0
st d, ret1_addr
jmp vm_immediate
resume_op_get_0:
ldi c, 15
ldi d, vm_load_word
jmp set_bank
padding28 db 0,0

; Native bank 29
; QR Terminal v2 word runtime
op_putc:
ldi c, 29
st c, ret2_bank
ldi d, resume_op_putc_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_putc_0:
ld a, U0
st a, 60
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_drop:
ldi c, 29
st c, ret2_bank
ldi d, resume_op_drop_0
st d, ret2_addr
ldi c, 26
ldi d, vm_pop
jmp set_bank
resume_op_drop_0:
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
op_jmp:
ldi c, 29
st c, ret1_bank
ldi d, resume_op_jmp_0
st d, ret1_addr
ldi c, 28
ldi d, vm_immediate
jmp set_bank
resume_op_jmp_0:
ldi c, 4
ldi d, vm_jump
jmp set_bank
; QR Terminal v2 native QR engine
op_beginbits:
ldi a, DATA_LO
st a, qptr0
ldi a, DATA_HI
st a, qptr1
clr a
st a, qpack
st a, qpackn
ldi c, 10
ldi d, vm_dispatch
jmp set_bank
; QR Terminal v2 word runtime
vm_increment_address:
ld a, M0
inc a
st a, M0
jnz vm_increment_done
ld a, M1
inc a
st a, M1
vm_increment_done:
ld c, ret3_bank
ld d, ret3_addr
jmp set_bank
; QR Terminal v2 native QR engine
render_column:
clr a
st a, qpack
ldi a, 1
st a, qbit
ld a, qrowbase
st a, qphysicaly
ldi c, 14
ldi d, render_pixel
jmp set_bank
; QR Terminal v2 word runtime
op_mod:
ldi a, 1
st a, opcode
ldi c, 13
ldi d, vm_divide
jmp set_bank
data_3840 db 26,214,28,238,6,222,17,194,24,217,11,203,28,166,21,128,21,176,4,128,2,246,29,246,26,128,22,128,22,176,23,128,13,200,12,200,20,180,19,128,12,128,29,152,23,176,29,172,24,170,15,194,27,128,23,224,29,128,14,198,1,128,29,192,9,128,2,128,10,128,11,128,18,128,6,128,25,128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_3968 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4096 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4224 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4352 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4480 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4608 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4736 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4864 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_4992 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5120 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5248 db 62,0,10,63,10,62,0,203,232,236,232,242,58,32,0,10,62,0,195,229,237,229,240,224,246,232,255,10,0,194,229,240,241,232,255,32,81,82,58,10,49,61,50,49,32,50,61,50,53,10,51,61,50,57,32,52,61,51,51,10,53,61,51,55,32,54,61,52,49,10,55,61,52,53,32,56,61,52,57,10,57,61,53,51,32,49,48,61,53,55,10,0,202,238,240,240,229,234,246,232,255,58,10,49,32,76,32,32,55,37,10,50,32,77,32,49,53,37,10,51,32,81,32,50,53,37,10,52
data_5376 db 32,72,32,51,48,37,10,0,210,232,239,32,226,226,238,228,224,58,10,49,32,214,232,244,240,251,10,50,32,192,235,244,224,226,232,242,10,51,32,67,80,49,50,53,49,10,0,81,82,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5504 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5632 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5760 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_5888 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6016 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6144 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6272 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6400 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6528 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6656 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6784 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_6912 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7040 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7168 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7296 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7424 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7552 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7680 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7808 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_7936 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8064 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8192 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8320 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8448 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8576 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8704 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8832 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_8960 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9088 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9216 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9344 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9472 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9600 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9728 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9856 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_9984 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10112 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10240 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10368 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10496 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10624 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10752 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_10880 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11008 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11136 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11264 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11392 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11520 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11648 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11776 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_11904 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_12032 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_12160 db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
data_12288 db 0,0,1,25,2,50,26,198,3,223,51,238,27,104,199,75,4,100,224,14,52,141,239,129,28,193,105,248,200,8,76,113,5,138,101,47,225,36,15,33,53,147,142,218,240,18,130,69,29,181,194,125,106,39,249,185,201,154,9,120,77,228,114,166,6,191,139,98,102,221,48,253,226,152,37,179,16,145,34,136,54,208,148,206,143,150,219,189,241,210,19,92,131,56,70,64,30,66,182,163,195,72,126,110,107,58,40,84,250,133,186,61,202,94,155,159,10,21,121,43,78,212,229,172,115,243,167,87
data_12416 db 7,112,192,247,140,128,99,13,103,74,222,237,49,197,254,24,227,165,153,119,38,184,180,124,17,68,146,217,35,32,137,46,55,63,209,91,149,188,207,205,144,135,151,178,220,252,190,97,242,86,211,171,20,42,93,158,132,60,57,83,71,109,65,162,31,45,67,216,183,123,164,118,196,23,73,236,127,12,111,246,108,161,59,82,41,157,85,170,251,96,134,177,187,204,62,90,203,89,95,176,156,169,160,81,11,245,22,235,122,117,44,215,79,174,213,233,230,231,173,232,116,214,244,234,168,80,88,175
data_12544 db 1,2,4,8,16,32,64,128,29,58,116,232,205,135,19,38,76,152,45,90,180,117,234,201,143,3,6,12,24,48,96,192,157,39,78,156,37,74,148,53,106,212,181,119,238,193,159,35,70,140,5,10,20,40,80,160,93,186,105,210,185,111,222,161,95,190,97,194,153,47,94,188,101,202,137,15,30,60,120,240,253,231,211,187,107,214,177,127,254,225,223,163,91,182,113,226,217,175,67,134,17,34,68,136,13,26,52,104,208,189,103,206,129,31,62,124,248,237,199,147,59,118,236,197,151,51,102,204
data_12672 db 133,23,46,92,184,109,218,169,79,158,33,66,132,21,42,84,168,77,154,41,82,164,85,170,73,146,57,114,228,213,183,115,230,209,191,99,198,145,63,126,252,229,215,179,123,246,241,255,227,219,171,75,150,49,98,196,149,55,110,220,165,87,174,65,130,25,50,100,200,141,7,14,28,56,112,224,221,167,83,166,81,162,89,178,121,242,249,239,195,155,43,86,172,69,138,9,18,36,72,144,61,122,244,245,247,243,251,235,203,139,11,22,44,88,176,125,250,233,207,131,27,54,108,216,173,71,142,1
data_12800 db 2,4,8,16,32,64,128,29,58,116,232,205,135,19,38,76,152,45,90,180,117,234,201,143,3,6,12,24,48,96,192,157,39,78,156,37,74,148,53,106,212,181,119,238,193,159,35,70,140,5,10,20,40,80,160,93,186,105,210,185,111,222,161,95,190,97,194,153,47,94,188,101,202,137,15,30,60,120,240,253,231,211,187,107,214,177,127,254,225,223,163,91,182,113,226,217,175,67,134,17,34,68,136,13,26,52,104,208,189,103,206,129,31,62,124,248,237,199,147,59,118,236,197,151,51,102,204,133
data_12928 db 23,46,92,184,109,218,169,79,158,33,66,132,21,42,84,168,77,154,41,82,164,85,170,73,146,57,114,228,213,183,115,230,209,191,99,198,145,63,126,252,229,215,179,123,246,241,255,227,219,171,75,150,49,98,196,149,55,110,220,165,87,174,65,130,25,50,100,200,141,7,14,28,56,112,224,221,167,83,166,81,162,89,178,121,242,249,239,195,155,43,86,172,69,138,9,18,36,72,144,61,122,244,245,247,243,251,235,203,139,11,22,44,88,176,125,250,233,207,131,27,54,108,216,173,71,142,1,2
data_13056 db 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,36,255,255,255,37,38,255,255,255,255,39,40,255,41,42,43,0,1,2,3,4,5,6,7,8,9,44,255,255,255,255,255,255,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255
data_13184 db 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255
data_13312 db 76,77,81,72,127,122,154,164,11,68,117,216,194,159,111,199,94,95,113,157,193,137,73,227,17,177,17,52,13,46,43,83,132,120,29,196,111,163,112,74,10,105,105,139,132,151,32,134,26,59,13,104,189,68,209,30,8,163,65,41,229,98,50,36,59,119,66,83,120,119,22,197,83,249,41,143,134,85,53,125,99,79,239,251,183,113,149,175,199,215,240,220,73,82,173,75,32,67,217,146,152,185,240,5,111,99,6,220,112,150,69,36,187,22,228,198,121,121,165,174,89,179,131,176,182,244,19,189
data_13440 db 69,40,28,137,29,123,67,253,86,218,230,26,145,245,122,118,169,70,178,237,216,102,115,150,229,73,130,72,61,43,206,1,237,247,127,217,144,117,246,51,183,4,136,98,199,152,77,56,206,24,145,40,209,117,233,42,135,68,70,144,146,77,43,94,252,9,28,13,18,251,208,150,103,174,100,41,167,12,247,56,117,119,233,127,181,100,121,147,176,74,58,197,212,246,77,73,195,192,75,98,5,70,103,177,22,217,138,51,181,246,72,25,18,46,228,74,216,195,11,106,130,150,0,0,0,0,0,0
data_13568 db 1,21,19,0,26,0,7,1,1,19,4,52,0,0,0,0,196,119,37,31,0,0,41,0,25,0,16,0,0,0,0,0,1,21,16,0,26,0,10,1,1,16,11,52,0,0,0,0,18,84,37,31,0,0,34,0,20,0,13,0,0,0,0,0,1,21,13,0,26,0,13,1,1,13,21,52,0,0,0,0,95,53,37,31,0,0,27,0,16,0,10,0,0,0,0,0,1,21,9,0,26,0,17,1,1,9,65,52,0,0,0,0,137,22,37,31,0,0,17,0,10,0,6,0,0,0,0,0
data_13696 db 2,25,34,0,44,0,10,1,1,34,11,52,2,6,18,0,196,119,111,33,0,0,77,0,47,0,31,0,0,0,0,0,2,25,28,0,44,0,16,1,1,28,49,52,2,6,18,0,18,84,111,33,0,0,63,0,38,0,25,0,0,0,0,0,2,25,22,0,44,0,22,1,1,22,120,52,2,6,18,0,95,53,111,33,0,0,48,0,29,0,19,0,0,0,0,0,2,25,16,0,44,0,28,1,1,16,192,52,2,6,18,0,137,22,111,33,0,0,34,0,20,0,13,0,0,0,0,0
data_13824 db 3,29,55,0,70,0,15,1,1,55,34,52,2,6,22,0,196,119,74,62,0,0,127,0,77,0,52,0,0,0,0,0,3,29,44,0,70,0,26,1,1,44,166,52,2,6,22,0,18,84,74,62,0,0,101,0,61,0,41,0,0,0,0,0,3,29,34,0,70,0,18,2,2,17,82,52,2,6,22,0,95,53,74,62,0,0,77,0,47,0,31,0,0,0,0,0,3,29,26,0,70,0,22,2,2,13,120,52,2,6,22,0,137,22,74,62,0,0,58,0,35,0,23,0,0,0,0,0
data_13952 db 4,33,80,0,100,0,20,1,1,80,100,52,2,6,26,0,196,119,222,66,0,0,187,0,114,0,77,0,0,0,0,0,4,33,64,0,100,0,18,2,2,32,82,52,2,6,26,0,18,84,222,66,0,0,149,0,90,0,61,0,0,0,0,0,4,33,48,0,100,0,26,2,2,24,166,52,2,6,26,0,95,53,222,66,0,0,111,0,67,0,45,0,0,0,0,0,4,33,36,0,100,0,16,4,4,9,49,52,2,6,26,0,137,22,222,66,0,0,82,0,50,0,33,0,0,0,0,0
data_14080 db 5,37,108,0,134,0,26,1,1,108,166,52,2,6,30,0,196,119,251,93,0,0,255,0,154,0,105,0,0,0,0,0,5,37,86,0,134,0,24,2,2,43,142,52,2,6,30,0,18,84,251,93,0,0,202,0,122,0,83,0,0,0,0,0,5,37,62,0,134,0,18,4,2,15,82,52,2,6,30,0,95,53,251,93,0,0,144,0,87,0,59,0,0,0,0,0,5,37,46,0,134,0,22,4,2,11,120,52,2,6,30,0,137,22,251,93,0,0,106,0,64,0,43,0,0,0,0,0
data_14208 db 6,41,136,0,172,0,18,2,2,68,82,52,2,6,34,0,196,119,177,99,0,0,66,1,195,0,133,0,0,0,0,0,6,41,108,0,172,0,16,4,4,27,49,52,2,6,34,0,18,84,177,99,0,0,255,0,154,0,105,0,0,0,0,0,6,41,76,0,172,0,24,4,4,19,142,52,2,6,34,0,95,53,177,99,0,0,178,0,108,0,73,0,0,0,0,0,6,41,60,0,172,0,28,4,4,15,192,52,2,6,34,0,137,22,177,99,0,0,139,0,84,0,57,0,0,0,0,0
data_14336 db 7,45,156,0,196,0,20,2,2,78,100,52,3,6,22,38,196,119,148,124,0,0,114,1,224,0,153,0,0,0,0,0,7,45,124,0,196,0,18,4,4,31,82,52,3,6,22,38,18,84,148,124,0,0,37,1,178,0,121,0,0,0,0,0,7,45,88,0,196,0,18,6,2,14,82,52,3,6,22,38,95,53,148,124,0,0,207,0,125,0,85,0,0,0,0,0,7,45,66,0,196,0,26,5,4,13,166,52,3,6,22,38,137,22,148,124,0,0,154,0,93,0,63,0,0,0,0,0
data_14464 db 8,49,194,0,242,0,24,2,2,97,142,52,3,6,24,42,196,119,188,133,0,0,205,1,23,1,191,0,0,0,0,0,8,49,154,0,242,0,22,4,2,38,120,52,3,6,24,42,18,84,188,133,0,0,109,1,221,0,151,0,0,0,0,0,8,49,110,0,242,0,22,6,4,18,120,52,3,6,24,42,95,53,188,133,0,0,3,1,157,0,107,0,0,0,0,0,8,49,86,0,242,0,26,6,4,14,166,52,3,6,24,42,137,22,188,133,0,0,202,0,122,0,83,0,0,0,0,0
data_14592 db 9,53,232,0,36,1,30,2,2,116,220,52,3,6,26,46,196,119,153,154,0,0,40,2,79,1,229,0,0,0,0,0,9,53,182,0,36,1,22,5,3,36,120,52,3,6,26,46,18,84,153,154,0,0,176,1,6,1,179,0,0,0,0,0,9,53,132,0,36,1,20,8,4,16,100,52,3,6,26,46,95,53,153,154,0,0,56,1,189,0,129,0,0,0,0,0,9,53,100,0,36,1,24,8,4,12,142,52,3,6,26,46,137,22,153,154,0,0,235,0,143,0,97,0,0,0,0,0
data_14720 db 10,57,18,1,90,1,18,4,2,68,82,52,3,6,28,50,196,119,211,164,0,0,140,2,139,1,14,1,0,0,0,0,10,57,216,0,90,1,26,5,4,43,166,52,3,6,28,50,18,84,211,164,0,0,1,2,55,1,212,0,0,0,0,0,10,57,154,0,90,1,24,8,6,19,142,52,3,6,28,50,95,53,211,164,0,0,108,1,221,0,150,0,0,0,0,0,10,57,122,0,90,1,28,8,6,15,192,52,3,6,28,50,137,22,211,164,0,0,32,1,174,0,118,0,0,0,0,0
data_14848 db 24,2,71,1,0,0,3,128,16,2,130,16,1,100,0,21,19,25,51,58,1,48,0,2,130,16,1,100,0,11,8,29,2,130,16,1,100,0,12,3,130,16,1,1,0,3,128,16,24,51,58,2,130,16,1,10,0,21,19,23,19,25,68,58,22,2,128,16,25,86,58,1,48,0,2,130,16,1,10,0,11,8,29,24,86,58,1,48,0,2,130,16,1,10,0,12,8,29,1,0,0,27,1,0,0,3,132,16,1,0,0,3,134,16,30,128,20,1,1,0,25,79,59,28,3,136,16,2
data_14976 db 136,16,1,27,0,20,25,148,58,1,12,0,29,1,0,0,27,24,148,58,2,136,16,1,10,0,20,25,211,58,2,132,16,1,1,0,21,19,23,25,179,58,22,2,138,16,2,132,16,21,19,25,193,58,1,10,0,29,2,132,16,27,24,193,58,30,130,20,1,0,0,3,132,16,1,0,0,3,134,16,24,76,59,2,136,16,1,8,0,20,25,5,59,1,0,0,2,134,16,21,25,2,59,2,132,16,1,10,0,11,3,132,16,2,134,16,1,1,0,9,3,134,16,1,8,0,29,24
data_15104 db 2,59,24,76,59,2,136,16,1,48,0,21,19,23,25,38,59,22,1,57,0,2,136,16,21,19,23,25,38,59,22,2,134,16,2,140,16,21,25,76,59,2,132,16,1,10,0,10,2,136,16,8,1,48,0,9,3,132,16,2,134,16,1,1,0,8,3,134,16,2,136,16,29,24,76,59,24,117,58,1,0,0,27,1,0,0,3,142,16,1,128,24,1,0,3,1,0,0,31,30,135,20,2,144,16,3,130,16,26,3,58,22,30,143,20,1,1,0,25,162,60,28,3,146,16,2,146,16
data_15232 db 1,27,0,20,25,162,59,1,12,0,29,1,128,24,1,0,3,1,0,0,31,1,0,0,3,142,16,1,0,0,27,24,162,59,2,146,16,1,10,0,20,25,196,59,1,0,0,2,142,16,21,25,193,59,1,10,0,29,1,1,0,27,24,193,59,24,159,60,2,146,16,1,8,0,20,25,247,59,1,0,0,2,142,16,21,25,244,59,2,142,16,1,1,0,9,3,142,16,1,128,24,2,142,16,8,1,0,0,6,1,8,0,29,24,244,59,24,159,60,1,0,0,3,148,16,2,150,16
data_15360 db 1,1,0,20,25,34,60,2,146,16,1,48,0,21,19,23,25,28,60,22,1,57,0,2,146,16,21,19,3,148,16,24,34,60,2,150,16,1,2,0,20,25,63,60,1,0,51,2,146,16,8,4,1,255,0,20,19,3,148,16,24,63,60,2,150,16,1,3,0,20,25,113,60,2,146,16,1,32,0,21,19,23,25,107,60,22,2,146,16,1,127,0,20,19,23,25,107,60,22,2,146,16,1,152,0,20,19,3,148,16,24,113,60,2,148,16,23,25,128,60,22,2,142,16,2,144,16,21
data_15488 db 25,159,60,1,128,24,2,142,16,8,2,146,16,6,2,142,16,1,1,0,8,3,142,16,2,146,16,29,24,159,60,24,115,59,1,0,0,27,2,152,16,2,154,16,33,2,156,16,2,154,16,8,3,156,16,1,0,0,27,1,128,27,1,128,1,1,0,0,31,32,1,0,0,3,156,16,2,150,16,1,1,0,20,25,208,61,1,1,0,1,4,0,3,154,16,3,152,16,26,166,60,22,2,158,16,1,10,0,21,25,3,61,2,142,16,1,10,0,3,154,16,3,152,16,26,166,60,22
data_15616 db 24,19,61,2,142,16,1,12,0,3,154,16,3,152,16,26,166,60,22,1,0,0,3,160,16,2,160,16,2,142,16,21,25,205,61,1,0,0,3,162,16,1,0,0,3,164,16,2,164,16,1,3,0,21,23,25,66,61,22,2,160,16,2,142,16,21,25,115,61,2,162,16,1,10,0,10,1,128,24,2,160,16,8,4,8,1,48,0,9,3,162,16,2,164,16,1,1,0,8,3,164,16,2,160,16,1,1,0,8,3,160,16,24,47,61,2,164,16,1,3,0,20,25,144,61,2,162,16
data_15744 db 1,10,0,3,154,16,3,152,16,26,166,60,22,24,144,61,2,164,16,1,2,0,20,25,173,61,2,162,16,1,7,0,3,154,16,3,152,16,26,166,60,22,24,173,61,2,164,16,1,1,0,20,25,202,61,2,162,16,1,4,0,3,154,16,3,152,16,26,166,60,22,24,202,61,24,25,61,24,208,61,2,150,16,1,2,0,20,25,150,62,1,2,0,1,4,0,3,154,16,3,152,16,26,166,60,22,2,158,16,1,10,0,21,25,7,62,2,142,16,1,9,0,3,154,16,3,152,16
data_15872 db 26,166,60,22,24,23,62,2,142,16,1,11,0,3,154,16,3,152,16,26,166,60,22,1,0,0,3,160,16,2,160,16,2,142,16,21,25,147,62,1,0,51,1,128,24,2,160,16,8,4,8,4,3,162,16,2,160,16,1,1,0,8,3,160,16,2,160,16,2,142,16,21,25,128,62,2,162,16,1,45,0,10,1,0,51,1,128,24,2,160,16,8,4,8,4,8,3,162,16,2,160,16,1,1,0,8,3,160,16,2,162,16,1,11,0,3,154,16,3,152,16,26,166,60,22,24,144,62
data_16000 db 2,162,16,1,6,0,3,154,16,3,152,16,26,166,60,22,24,29,62,24,150,62,2,150,16,1,3,0,20,25,50,63,1,7,0,1,4,0,3,154,16,3,152,16,26,166,60,22,1,22,0,1,8,0,3,154,16,3,152,16,26,166,60,22,1,4,0,1,4,0,3,154,16,3,152,16,26,166,60,22,2,158,16,1,10,0,21,25,237,62,2,142,16,1,8,0,3,154,16,3,152,16,26,166,60,22,24,253,62,2,142,16,1,16,0,3,154,16,3,152,16,26,166,60,22,1,0,0
data_16128 db 3,160,16,2,160,16,2,142,16,21,25,47,63,1,128,24,2,160,16,8,4,1,8,0,3,154,16,3,152,16,26,166,60,22,2,160,16,1,1,0,8,3,160,16,24,3,63,24,50,63,2,166,16,1,8,0,10,2,156,16,9,3,168,16,1,4,0,2,168,16,21,25,83,63,1,4,0,3,168,16,24,83,63,1,0,0,2,168,16,21,25,112,63,1,0,0,2,168,16,3,154,16,3,152,16,26,166,60,22,24,112,63,2,156,16,1,7,0,14,1,0,0,20,19,25,154,63,1
data_16256 db 0,0,1,8,0,2,156,16,1,7,0,14,9,3,154,16,3,152,16,26,166,60,22,24,154,63,1,236,0,3,162,16,2,156,16,2,166,16,1,8,0,10,21,25,203,63,2,162,16,1,8,0,3,154,16,3,152,16,26,166,60,22,2,162,16,1,253,0,16,3,162,16,24,160,63,1,0,0,27,2,170,16,1,8,0,8,4,3,172,16,2,170,16,1,9,0,8,4,3,174,16,2,170,16,1,10,0,8,5,3,176,16,1,0,0,3,178,16,1,0,0,3,180,16,2,180,16,2
data_16384 db 182,16,21,25,121,64,2,174,16,3,184,16,2,180,16,2,172,16,21,19,25,36,64,2,184,16,1,1,0,8,3,184,16,24,36,64,1,128,31,2,180,16,1,4,0,10,8,2,178,16,7,1,128,31,2,180,16,1,4,0,10,8,1,2,0,8,2,184,16,6,1,128,27,2,178,16,8,2,184,16,2,186,16,2,176,16,1,0,29,2,180,16,2,186,16,10,8,34,2,178,16,2,184,16,8,3,178,16,2,180,16,1,1,0,8,3,180,16,24,252,63,1,0,0,3,188,16,1
data_16512 db 0,0,3,190,16,2,174,16,2,190,16,21,19,25,1,65,1,0,0,3,180,16,2,180,16,2,182,16,21,25,244,64,2,190,16,1,128,31,2,180,16,1,4,0,10,8,1,2,0,8,4,21,25,231,64,1,128,31,2,180,16,1,4,0,10,8,5,3,192,16,1,0,30,2,188,16,8,1,128,27,2,192,16,8,2,190,16,8,4,6,2,188,16,1,1,0,8,3,188,16,24,231,64,2,180,16,1,1,0,8,3,180,16,24,150,64,2,190,16,1,1,0,8,3,190,16,24,133
data_16640 db 64,1,0,0,3,190,16,2,190,16,2,186,16,21,25,93,65,1,0,0,3,180,16,2,180,16,2,182,16,21,25,80,65,1,0,30,2,188,16,8,1,0,29,2,180,16,2,186,16,10,8,2,190,16,8,4,6,2,188,16,1,1,0,8,3,188,16,2,180,16,1,1,0,8,3,180,16,24,23,65,2,190,16,1,1,0,8,3,190,16,24,7,65,1,0,0,27,2,194,16,2,196,16,1,2,0,2,198,16,15,35,1,0,0,27,1,4,0,13,3,200,16,1,4,0,2,200,16
data_16768 db 21,19,25,109,66,1,4,0,13,3,202,16,1,4,0,2,202,16,21,19,25,96,66,2,204,16,2,202,16,8,3,206,16,2,208,16,2,200,16,8,3,210,16,2,206,16,1,0,0,21,19,23,25,216,65,22,2,206,16,2,212,16,21,23,25,216,65,22,2,210,16,1,0,0,21,19,23,25,216,65,22,2,210,16,2,212,16,21,25,83,66,2,202,16,3,214,16,2,200,16,3,216,16,2,214,16,1,0,0,21,25,251,65,2,214,16,13,3,214,16,24,251,65,2,216,16,1,0
data_16896 db 0,21,25,15,66,2,216,16,13,3,216,16,24,15,66,2,214,16,3,218,16,2,218,16,2,216,16,21,25,40,66,2,216,16,3,218,16,24,40,66,2,206,16,2,210,16,2,218,16,1,2,0,20,19,23,25,67,66,22,2,218,16,1,4,0,20,19,3,198,16,3,196,16,3,194,16,26,97,65,22,24,83,66,2,202,16,1,1,0,8,3,202,16,24,140,65,2,200,16,1,1,0,8,3,200,16,24,122,65,1,0,0,27,1,2,0,13,3,220,16,1,2,0,2,220,16,21,19
data_17024 db 25,75,67,1,2,0,13,3,222,16,1,2,0,2,222,16,21,19,25,62,67,1,1,0,3,224,16,2,222,16,1,1,0,13,20,23,19,25,176,66,22,2,222,16,1,1,0,20,23,25,203,66,22,2,220,16,1,1,0,13,21,19,23,25,203,66,22,1,1,0,2,220,16,21,19,25,215,66,1,0,0,3,224,16,24,215,66,2,220,16,1,1,0,13,20,23,19,25,236,66,22,2,220,16,1,1,0,20,23,25,7,67,22,2,222,16,1,1,0,13,21,19,23,25,7,67,22,1
data_17152 db 1,0,2,222,16,21,19,25,19,67,1,0,0,3,224,16,24,19,67,2,226,16,2,222,16,8,2,228,16,2,220,16,8,2,224,16,3,198,16,3,196,16,3,194,16,26,97,65,22,2,222,16,1,1,0,8,3,222,16,24,138,66,2,220,16,1,1,0,8,3,220,16,24,120,66,1,0,0,27,1,0,32,1,0,16,1,0,0,31,1,0,0,3,230,16,2,230,16,2,212,16,21,25,178,67,1,6,0,2,230,16,2,230,16,1,1,0,14,1,0,0,20,3,198,16,3,196,16
data_17280 db 3,194,16,26,97,65,22,2,230,16,1,6,0,2,230,16,1,1,0,14,1,0,0,20,3,198,16,3,196,16,3,194,16,26,97,65,22,2,230,16,1,1,0,8,3,230,16,24,95,67,1,3,0,1,3,0,3,208,16,3,204,16,26,115,65,22,2,212,16,1,4,0,9,1,3,0,3,208,16,3,204,16,26,115,65,22,1,3,0,2,212,16,1,4,0,9,3,208,16,3,204,16,26,115,65,22,2,170,16,1,12,0,8,4,3,232,16,1,0,0,3,234,16,2,234,16,2,232
data_17408 db 16,21,25,165,68,1,0,0,3,236,16,2,236,16,2,232,16,21,25,152,68,2,234,16,1,0,0,20,23,25,40,68,22,2,236,16,1,0,0,20,23,19,25,98,68,22,2,234,16,1,0,0,20,23,25,69,68,22,2,236,16,2,232,16,1,1,0,9,20,23,19,25,98,68,22,2,234,16,2,232,16,1,1,0,9,20,23,25,98,68,22,2,236,16,1,0,0,20,19,25,139,68,2,170,16,1,13,0,8,2,234,16,8,4,2,170,16,1,13,0,8,2,236,16,8,4,3,228
data_17536 db 16,3,226,16,26,113,66,22,24,139,68,2,236,16,1,1,0,8,3,236,16,24,11,68,2,234,16,1,1,0,8,3,234,16,24,251,67,2,170,16,1,16,0,8,5,3,238,16,1,0,0,3,230,16,2,230,16,1,15,0,21,25,216,69,2,238,16,2,230,16,18,1,1,0,14,3,240,16,2,230,16,1,6,0,21,25,241,68,1,8,0,2,230,16,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24,241,68,2,230,16,1,6,0,20,25,20,69,1,8,0,1,7
data_17664 db 0,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24,20,69,2,230,16,1,7,0,20,25,55,69,1,8,0,1,8,0,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24,55,69,2,230,16,1,8,0,20,25,90,69,1,7,0,1,8,0,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24,90,69,2,230,16,1,9,0,21,19,25,130,69,1,14,0,2,230,16,9,1,8,0,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24
data_17792 db 130,69,2,230,16,1,8,0,21,25,173,69,2,212,16,1,1,0,9,2,230,16,9,1,8,0,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,24,203,69,1,8,0,2,212,16,1,15,0,9,2,230,16,8,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,2,230,16,1,1,0,8,3,230,16,24,182,68,1,8,0,2,212,16,1,8,0,9,1,1,0,3,198,16,3,196,16,3,194,16,26,97,65,22,2,158,16,1,7,0,21,19,25,168,70,2,170,16
data_17920 db 1,18,0,8,5,3,242,16,2,170,16,1,20,0,8,4,3,244,16,1,0,0,3,230,16,2,230,16,1,18,0,21,25,165,70,2,230,16,1,16,0,21,25,62,70,2,242,16,2,230,16,18,1,1,0,14,3,240,16,24,80,70,2,244,16,2,230,16,1,16,0,9,18,1,1,0,14,3,240,16,2,212,16,1,11,0,9,2,230,16,1,3,0,12,8,3,246,16,2,230,16,1,3,0,11,3,248,16,2,246,16,2,248,16,2,240,16,3,198,16,3,196,16,3,194,16,26,97
data_18048 db 65,22,2,248,16,2,246,16,2,240,16,3,198,16,3,196,16,3,194,16,26,97,65,22,2,230,16,1,1,0,8,3,230,16,24,25,70,24,168,70,1,0,0,27,1,5,0,3,250,16,30,146,20,26,187,60,22,26,207,63,22,26,79,67,22,2,212,16,2,252,16,37,2,212,16,38,1,6,0,3,250,16,2,212,16,39,1,128,24,1,0,3,1,0,0,31,1,128,27,1,128,1,1,0,0,31,1,0,29,1,0,1,1,0,0,31,1,0,30,1,128,1,1,0,0,31,1,0
data_18176 db 0,27,1,12,0,29,1,1,0,25,49,72,1,0,0,3,142,16,1,1,0,3,250,16,30,157,20,1,10,0,1,2,0,3,140,16,3,138,16,26,102,58,3,158,16,2,158,16,1,0,0,20,19,25,46,72,1,2,0,3,250,16,30,220,20,1,4,0,1,1,0,3,140,16,3,138,16,26,102,58,3,254,16,2,254,16,1,0,0,20,19,25,43,72,1,3,0,3,250,16,30,8,21,1,3,0,1,1,0,3,140,16,3,138,16,26,102,58,3,150,16,2,150,16,1,0,0,20
data_18304 db 19,25,40,72,1,0,53,2,158,16,1,1,0,9,1,4,0,10,2,254,16,8,1,1,0,9,1,32,0,10,8,3,170,16,2,170,16,1,1,0,8,4,3,212,16,2,170,16,1,2,0,8,5,3,166,16,2,170,16,1,4,0,8,5,3,252,16,2,170,16,1,6,0,8,4,3,186,16,2,170,16,1,7,0,8,4,3,182,16,2,170,16,1,22,0,8,2,150,16,1,1,0,9,1,2,0,10,8,5,3,144,16,1,4,0,3,250,16,30,47,21,2,158,16,3,130,16,26
data_18432 db 3,58,22,1,45,0,29,1,0,52,2,254,16,8,1,1,0,9,4,29,1,10,0,29,26,83,59,25,37,72,26,172,70,22,24,37,72,24,40,72,24,43,72,24,46,72,24,6,71,1,0,0,27
